### ISSUE TITLE
Task 11: -	An authenticated principal do the same as an anonymous principal.

### ISSUE THREAD

**Issue by sardongui** [sardongui/Acme-FleaMarket-D02#11]
-	An authenticated principal must be able to:
o	Do the same as an anonymous principal.

**Comment by danmarsua1** [comment]
Terminada la funcionalidad de news para el rol de autenticado. Estoy pendiente de las otras dos funcionalidades relacionadas con material sheet y tool sheet, por la duda que te comentaba que ibamos a ver hoy, y termino.
