### ISSUE TITLE
Task 17: Banner

### ISSUE THREAD

**Issue by sardongui** [sardongui/Acme-FleaMarket-D02#17]
-	The system must store banners, which consists of a picture, a slogan, a target URL, and an op-tional credit card.  The system must store the following information regarding credit cards: holder name, number, brand, expiration date, and CVV code.

**Comment by danmarsua1** [comment]
@sardongui en esta funcionalidad solo creo las entidades Banner y CreditCard y ya está? Ni vistas ni nada no? no pone nada de list o show

**Comment by sardongui** [comment]
@danmarsua1 si, sería solo eso, en las proximas entregas seguramente te pidan implementar el list, show o la funcion que sea
